=== arXiv/zzzArchived_arxiv-references/schema/ExtractedReference.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "ExtractedReference",
    "type": "object",
    "required": [
        "reftype",
        "raw"
    ],
    "properties": {
        "title": {
            "description": "The title of the reference.",
            "type": "string"
        },
        "raw": {
            "description": "The un-parsed reference string.",
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "surname": {
                        "type": "string"
                    },
                    "givennames": {
                        "type": "string"
                    },
                    "prefix": {
                        "type": "string"
                    },
                    "suffix": {
                        "type": "string"
                    }
                }
            }
        },
        "reftype": {
            "description": "The type of work to which the reference refers.",
            "type": "string"
        },
        "doi": {
            "type": "string"
        },
        "volume": {
            "type": "string"
        },
        "issue": {
            "type": "string"
        },
        "pages": {
            "type": "string"
        },
        "source": {
            "type": "string"
        },
        "year": {
            "type": "string"
        },
        "identifiers": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "identifer_type": {
                        "description": "E.g. ISBN, ISSN, URI",
                        "type": "string"
                    },
                    "identifier": {
                        "type": "string"
                    }
                }
            }
        }
    }
}

=== arXiv/zzzArchived_arxiv-references/tests/data/1702.07336.cermine.json
[
    {
        "authors": [
            {
                "givennames": "E.",
                "prefix": "",
                "suffix": "",
                "surname": "Betzig"
            }
        ],
        "doi": "",
        "identifiers": [
            {
                "identifier": "",
                "identifier_type": ""
            }
        ],
        "issue": "1642",
        "pages": "",
        "raw": "E. Betzig et al., Science 313, 1642 (2006)",
        "reftype": "",
        "source": "Science",
        "title": "",
        "volume": "313",
        "year": "2006"
    },
    {
        "authors": [
            {
                "givennames": "M. J.",
                "prefix": "",
                "suffix": "",
                "surname": "Rust"
            },
            {
                "givennames": "M.",
                "prefix": "",
                "suffix": "",
                "surname": "Bates"
            },
            {
                "givennames": "X.",
                "prefix": "",
                "suffix": "",
                "surname": "Zhuang"
            }
        ],
        "doi": "",
        "identifiers": [
            {
                "identifier": "",
                "identifier_type": ""
            }
        ],
        "issue": "793",
        "pages": "",
        "raw": "M. J. Rust, M. Bates, and X. Zhuang, Nat. Methods 3, 793 (2006)",
        "reftype": "",
        "source": "Nat. Methods",
        "title": "",
        "volume": "3",
        "year": "2006"
    },
    {
        "authors": [
            {
                "givennames": "S. W.",
                "prefix": "",
                "suffix": "",
                "surname": "Hell"
            },
            {
                "givennames": "J.",
                "prefix": "",
                "suffix": "",
                "surname": "Wichmann"
            }
        ],
        "doi": "",
        "identifiers": [
            {
                "identifier": "",
                "identifier_type": ""
            }
        ],
        "issue": "780",
        "pages": "",
        "raw": "S. W. Hell and J. Wichmann, Opt. Lett. 19, 780 (1994)",
        "reftype": "",
        "source": "",
        "title": "",
        "volume": "19",
        "year": "1994"
    },
    {
        "authors": [
            {
                "givennames": "P.",
                "prefix": "",
                "suffix": "",
                "surname": "Kner"
            },
            {
                "givennames": "B. B.",
                "prefix": "",
                "suffix": "",
                "surname": "Chhun"
            },
            {
                "givennames": "E. R.",
                "prefix": "",
                "suffix": "",
                "surname": "Gri s"
            },
            {
                "givennames": "M. G. L.",
                "prefix": "",
                "suffix": "",
                "surname": "Gustafsson"
            }
        ],
        "doi": "",
        "identifiers": [
            {
                "identifier": "",
                "identifier_type": ""
            }
        ],
        "issue": "339",
        "pages": "",
        "raw": "P. Kner, B. B. Chhun, E. R. Gri s, L. Winoto, and M. G. L. Gustafsson, Nat. Methods 6, 339 (2009)",
        "reftype": "",
        "source": "Nat. Methods",
        "title": "",
        "volume": "6",
        "year": "2009"
    },
    {
        "authors": [
            {
                "givennames": "B.-C.",
                "prefix": "",
                "suffix": "",
                "surname": "Chen"
            },
            {
                "givennames": "W. R.",
                "prefix": "",
                "suffix": "",
                "surname": "Legant"
            },
            {
                "givennames": "K.",
                "prefix": "",
                "suffix": "",
                "surname": "Wang"
            },
            {
                "givennames": "L.",
                "prefix": "",
                "suffix": "",
                "surname": "Shao"
            },
            {
                "givennames": "D. E.",
                "prefix": "",
                "suffix": "",
                "surname": "Milkie"
            },
            {
                "givennames": "M. W.",
                "prefix": "",
                "suffix": "",
                "surname": "Davidson"
            },
            {
                "givennames": "C.",
                "prefix": "",
                "suffix": "",
                "surname": "Janetopoulos"
            },
            {
                "givennames": "X. S.",
                "prefix": "",
                "suffix": "",
                "surname": "Wu"
            },
            {
                "givennames": "J. A.",
                "prefix": "",
                "suffix": "",
                "surname": "Hammer"
            },
            {
                "givennames": "Z.",
                "prefix": "",
                "suffix": "",
                "surname": "Liu"
            }
        ],
        "doi": "",
        "identifiers": [
            {
                "identifier": "",
                "identifier_type": ""
            }
        ],
        "issue": "1257998",
        "pages": "",
        "raw": "B.-C. Chen, W. R. Legant, K. Wang, L. Shao, D. E. Milkie, M. W. Davidson, C. Janetopoulos, X. S. Wu, J. A. Hammer, Z. Liu, et al., Science 346, 1257998 (2014)",
        "reftype": "",
        "source": "Science",
        "title": "",
        "volume": "346",
        "year": "2014"
    },
    {
        "authors": [
            {
                "givennames": "S. S.",
                "prefix": "",
                "suffix": "",
                "surname": "Rogers"
            },
            {
                "givennames": "T. A.",
                "prefix": "",
                "suffix": "",
                "surname": "Waigh"
            },
            {
                "givennames": "X.",
                "prefix": "",
                "suffix": "",
                "surname": "Zhao"
            },
            {
                "givennames": "and J. R.",
                "prefix": "",
                "suffix": "",
                "surname": "Lu"
            }
        ],
        "doi": "",
        "identifiers": [
            {
                "identifier": "",
                "identifier_type": ""
            }
        ],
        "issue": "220",
        "pages": "",
        "raw": "S. S. Rogers, T. A. Waigh, X. Zhao, and J. R. Lu, Physical Biology 4, 220 (2007)",
        "reftype": "",
        "source": "Physical Biology",
        "title": "",
        "volume": "4",
        "year": "2007"
    },
    {
        "authors": [
            {
                "givennames": "R.",
                "prefix": "",
                "suffix": "",
                "surname": "Pathasarathy"
            }
        ],
        "doi": "",
        "identifiers": [
            {
                "identifier": "",
                "identifier_type": ""
            }
        ],
        "issue": "724",
        "pages": "",
        "raw": "R. Pathasarathy, Nat. Methods 9, 724 (2012)",
        "reftype": "",
        "source": "Nat. Methods",
        "title": "",
        "volume": "9",
        "year": "2012"
    },
    {
        "authors": [
            {
                "givennames": "F.",
                "prefix": "",
                "suffix": "",
                "surname": "Gru"
            },
            {
                "givennames": "M.",
                "prefix": "",
                "suffix": "",
                "surname": "Hausmann"
            }
        ],
        "doi": "",
        "identifiers": [
            {
                "identifier": "",
                "identifier_type": ""
            }
        ],
        "issue": "",
        "pages": "5",
        "raw": "F. Gru \u007fll, M. Kirchgessner, R. Kaufmann, M. Hausmann, and U. Kebschull, in Field Programmable Logic and Applications (FPL), 2011 International Conference on (IEEE, 2011), pp. 1 { 5",
        "reftype": "",
        "source": "Field Programmable Logic and Applications (FPL) 2011 International Conference on (IEEE",
        "title": "",
        "volume": "1",
        "year": "2011"
    },
    {
        "authors": [
            {
                "givennames": "S. M.",
                "prefix": "",
                "suffix": "",
                "surname": "Anthony"
            },
            {
                "givennames": "S.",
                "prefix": "",
                "suffix": "",
                "surname": "Granick"
            }
        ],
        "doi": "",
        "identifiers": [
            {
                "identifier": "",
                "identifier_type": ""
            }
        ],
        "issue": "8152",
        "pages": "",
        "raw": "S. M. Anthony and S. Granick, Langmuir 25, 8152 (2009)",
        "reftype": "",
        "source": "",
        "title": "",
        "volume": "25",
        "year": "2009"
    },
    {
        "authors": [
            {
                "givennames": "C. S.",
                "prefix": "",
                "suffix": "",
                "surname": "Smith"
            },
            {
                "givennames": "N.",
                "prefix": "",
                "suffix": "",
                "surname": "Joseph"
            },
            {
                "givennames": "B.",
                "prefix": "",
                "suffix": "",
                "surname": "Rieger"
            },
            {
                "givennames": "K. A.",
                "prefix": "",
                "suffix": "",
                "surname": "Lidke"
            }
        ],
        "doi": "",
        "identifiers": [
            {
                "identifier": "",
                "identifier_type": ""
            }
        ],
        "issue": "373",
        "pages": "",
